// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsYseHBbIPy8wB2NMFbzo9l83iKkvuZ14',
    appId: '1:1011843012378:web:7103effedce7698c38bea3',
    messagingSenderId: '1011843012378',
    projectId: 'technical-assessment-6b27b',
    authDomain: 'technical-assessment-6b27b.firebaseapp.com',
    storageBucket: 'technical-assessment-6b27b.appspot.com',
    measurementId: 'G-7Y74FT4957',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1bVEWF6TzOlDoVoVjtMbg86-XVsARMqM',
    appId: '1:1011843012378:android:d4b299ef926d840938bea3',
    messagingSenderId: '1011843012378',
    projectId: 'technical-assessment-6b27b',
    storageBucket: 'technical-assessment-6b27b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAskfc-E3ngFLDVLvaZNDD5KZXDb7JNpgE',
    appId: '1:1011843012378:ios:4906bab60ede744b38bea3',
    messagingSenderId: '1011843012378',
    projectId: 'technical-assessment-6b27b',
    storageBucket: 'technical-assessment-6b27b.appspot.com',
    iosBundleId: 'com.example.technicalAssessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAskfc-E3ngFLDVLvaZNDD5KZXDb7JNpgE',
    appId: '1:1011843012378:ios:4906bab60ede744b38bea3',
    messagingSenderId: '1011843012378',
    projectId: 'technical-assessment-6b27b',
    storageBucket: 'technical-assessment-6b27b.appspot.com',
    iosBundleId: 'com.example.technicalAssessment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsYseHBbIPy8wB2NMFbzo9l83iKkvuZ14',
    appId: '1:1011843012378:web:b18b3acc0993b62238bea3',
    messagingSenderId: '1011843012378',
    projectId: 'technical-assessment-6b27b',
    authDomain: 'technical-assessment-6b27b.firebaseapp.com',
    storageBucket: 'technical-assessment-6b27b.appspot.com',
    measurementId: 'G-PJK9ZX7F99',
  );
}
